---
# tasks file for default
- name: playbook de usuarios
  include: user.yaml

- name: pacotes padroes para debian
  include: debian.yaml
  when: ansible_os_family == "Debian"

- name: pacotes padroes para centos
  include: centos.yaml
  when: ansible_os_family == "RedHat"

- name: arquivos padroes para todos maquinas
  include: arquivo.yaml
