--- 
- name: criando um servidor web
  hosts: all
  tasks:
    - name: usuarios comuns do sistema
      user:
        name: "{{ item }}" 
        password:
        shell: /bin/bash
      with_items:
        - devops
        - developer
        - rafael_rosa


    - name: instalando apache2
      package:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: instalando httpd
      package:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
