---
- name: utilizando variavel na playbook
  hosts: "{{maquina}}"
  vars:
    - maquina: default
    - pack: pack
  tasks:
    - name: aplicando pacote
      package:
        name: "{{pack}}"
        state: present
